w = input('Digite algo: ')
print(type(w))
print(f'{w} é numerico?: ',w.isnumeric())
print(f'{w} é alfabetico?: ',w.isalpha())
print(f'{w} é alfa-numerico?: ',w.isalnum())
print(f'{w} foi digitado em maiusculo?: ',w.isupper())
print(f'{w} foi digitado em minusculo?: ',w.islower())
print(f'{w} é somente espaço?: ',w.isspace())
print(f'{w} tem capitalizado?: ',w.istitle())
